# Generated by Django 5.1.5 on 2025-03-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='operator',
        ),
    ]
