# Generated by Django 5.1.5 on 2025-04-23 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_remove_phonenumber_operator_alter_phonenumber_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='stats.company')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_number', to='stats.phonenumber')),
            ],
        ),
    ]
