# Generated by Django 5.1.5 on 2025-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_companyphonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personnel_number',
            field=models.CharField(max_length=50),
        ),
    ]
